### ISSUE TITLE
could you share the codes or benchmarks?

### ISSUE THREAD

**Issue by Ocean23333** [Xuchen-Li/DTLLM-VLT#2]
Great job!
Will the datasets you've produced  or the code be released as open source?

**Comment by Ocean23333** [comment]
Thank you for your prompt response and your work！

**Comment by Ocean23333** [comment]
I think it would be better to package the dataset in zips

**Comment by Xuchen-Li** [comment]
Thank you for your suggestion, I will upload the dataset in zips format today.

**Comment by Xuchen-Li** [comment]
@Ocean23333 Hello, you can find the dataset in zip format in the train/test_val folders respectively (train.zip and val_test.zip).

**Comment by Ocean23333** [comment]
Thank you for your prompt response and action！
